### ISSUE TITLE
Thumbkit::Adapters::CarrierWave#thumbkit intermittently gets called before there's a cache_key

### ISSUE THREAD

**Issue by adrianpike** [carnesmedia/thumbkit#13]
Seems like it's happening ~75% of the time, so the app's pretty much unusable :(

The setup:

```
#/thumbkit-8ad4994ecd82/lib/thumbkit/adapters/carrier_wave.rb
 def thumbkit(*args)
  options = thumbkit_options(args)
      p "CALLING THUMBKIT, #{cached?}"
  cache_stored_file! if !cached?
  thumbkit = Thumbkit.new(current_path)
  result = thumbkit.write_thumbnail(nil, options)
  @file = CarrierWave::SanitizedFile.new(result)
end


#/carrierwave-557528da6a08/lib/carrierwave/uploader/cache.rb
def cache_id=(cache_id)
    p "SETTING CACHE_ID TO #{cache_id}"
    raise CarrierWave::InvalidParameter, "invalid cache id" unless cache_id =~ /\A[\d]{8}\-[\d]{4}\-[\d]+\-[\d]{4}\z/
    @cache_id = cache_id
end
```

The results:

https://gist.github.com/548679b1766f1cc8609d

Seems like CarrierWave isn't being consistent with order for some ungodly reason? @amiel, any chance you can take a peek? I've been hammering against it for a few hours and I'm gonna have to throw in the towel tonight.

I just tried a last-minute hack of wrapping everything in the thumbkit in a if cached? block and seeing how that runs overnight for TT

edit:// nope, just watched a pile of uploads roll in and bork. Maybe Fog is forking on big files somehow?

**Comment by amiel** [comment]
Turns out this is a carrierwave bug introduced here
https://github.com/jnicklas/carrierwave/commit/a95e5daf6ed7c63a9620effe533d1ff61f2e916f#lib/carrierwave/uploader/download.rb
